//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TryIt.BowlService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BowlService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addToBowl", ReplyAction="http://tempuri.org/IService1/addToBowlResponse")]
        string addToBowl(string item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/removeFromBowl", ReplyAction="http://tempuri.org/IService1/removeFromBowlResponse")]
        string removeFromBowl(string item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/checkOutConfirm", ReplyAction="http://tempuri.org/IService1/checkOutConfirmResponse")]
        bool checkOutConfirm();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : TryIt.BowlService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<TryIt.BowlService.IService1>, TryIt.BowlService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string addToBowl(string item) {
            return base.Channel.addToBowl(item);
        }
        
        public string removeFromBowl(string item) {
            return base.Channel.removeFromBowl(item);
        }
        
        public bool checkOutConfirm() {
            return base.Channel.checkOutConfirm();
        }
    }
}
